name: AshMan
author: zzz
main: net.mcbbs.zzz1999.AshMan.Main
version: "1.0.0"
api: ["1.0.0"]
description: "一个清理多余生物和掉落物的插件"

permissions:
 AshMan.Commands.clean:
  default: op
  description: "清理多余的生物和掉落物的权限"
